imports:
    - { resource: defaults.yml }
    - { resource: custom.yml }
    - { resource: security.yml }
    - { resource: extjs.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          
      resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    # due to ajax form handling csrf protection is disabled, @todo do it better way
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      
      engines: ['twig'] 
      assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

sensio_framework_extra:
    view:   { annotations: false }
    router: { annotations: true }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Hatimeria\Bundle\CMFBundle\Entity\User    
    
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 123456879
    secret: s3cr3t
    cookie: true
    permissions: [email, user_birthday, user_location]    
    
fos_js_routing:
    routes_to_expose: [fos_user_security_check, fos_user_security_logout, homepage, hatimeria_admin]    
    
zenstruck_content:
    use_form: true
    use_controller: true
    node_class: Hatimeria\Bundle\CMFBundle\Entity\ContentNode
    content_types:
      cms_page: Hatimeria\Bundle\CMFBundle\Entity\CmsPage      
      
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    
          encoding: utf-8
    image:
        enabled:    false
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []      
        
hatimeria_newsletter:
    sender: %hatimeria_newsletter_sender%

hatimeria_remotelog:
    host: %remotelog_host%                               # (required) remotelog application server hos
    place: 'Framework Remotelog test enviroment'         # (required) Some information about project to identify log
    route: '/api/monitoring'                             # If you need you can provide more spcific path (concept)
    level: ERROR                                         # You can define logging level same way as you configure your monolog handler
    cli: true                                            # Catch cli php errors
    enabled: %remotelog_enabled%

fos_rest:
    routing_loader:
        default_format: json
    view:
        default_engine: twig
        formats:
            json: true
        templating_formats:
            json: false
            html: true
